### ISSUE TITLE
開発準備

### ISSUE THREAD

**Issue by susatthi** [IkemotoNanako/repeat_notification_app#1]
次の開発準備をやる。

## TODO

- [x] GitHubリポジトリの書き込み権限をもらう
- [x] タスク分解してIssue登録する
- [x] fvmの導入
- [x] Makefileの導入
- [x] .vscodeの導入
- [x] PRテンプレートの作成
- [x] 不要なプラットフォームフォルダの削除
- [x] アーキテクチャ＋フォルダ構成の決定
- [x] pedantic_mono（lint）の導入
- [x] 開発フローを決定する
- [x] README更新

## 使用するパッケージ（重要なもの）

- riverpod + riverpod_generator
- freezed
- auto_route
- isar

**Comment by susatthi** [comment]
@IkemotoNanako 

まず最初に本Issueで開発準備をしていきます！

① 最初のコメントの開発準備用のタスク一覧をご確認ください。過不足あればご指摘お願いします！
② 私に本IssueのWrite権限をください〜
自分をIssueアサインしたいのと、git push 出来なかったです
③ PR（PullRequest）のテンプレートを作成してよいでしょうか？
④ 対応プラットフォームは iOS と Android だけでよいでしょうか？他プラットフォームのフォルダは削除したく。
⑤ アーキテクチャ＋フォルダ構成の指定はありますか？指定がなければ私の好きなようにやっちゃってよいでしょうか？
⑥ 開発フローは [git-flow](https://www.atlassian.com/ja/git/tutorials/comparing-workflows/gitflow-workflow#:~:text=Gitflow%20%E3%81%A8%E3%81%AF%E3%80%81%E3%83%95%E3%82%A3%E3%83%BC%E3%83%81%E3%83%A3%E3%83%BC%20%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81,%E8%A6%8F%E6%A8%A1%E3%81%AA%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%81%8C%E3%81%82%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82) でよいでしょうか？

**Comment by IkemotoNanako** [comment]
@susatthi 
ありがとうございます！

1. 良さそうです！
2. ググってもよくわからなかったのでとりあえずメール招待を送ってみました！足りなければ教えてください。。。
3. お願いします！
4. 大丈夫です！削除お願いします！
5. ないです！お任せします！
6. 良いです！それしか知らないですので！

**Comment by susatthi** [comment]
@IkemotoNanako 

>1. 良さそうです！

ご確認ありがとうございました！

>2. ググってもよくわからなかったのでとりあえずメール招待を送ってみました！足りなければ教えてください。。。

write権限もらえました。ありがとうございます！

>3. お願いします！

承知しました！

>4. 大丈夫です！削除お願いします！

承知しました！

>5. ないです！お任せします！

やっちゃいます！

>6. 良いです！それしか知らないですので！

承知しました！

⑦ ⑥に関連して、git-flowではデフォルトブランチは `develop` になるので対応してもらえないでしょうか？私は権限無くてできないので。。

**Comment by IkemotoNanako** [comment]
@susatthi 
developにしてみました！どうでしょうか？

**Comment by susatthi** [comment]
@IkemotoNanako 

develop になりました！ありがとうございます！
ではまずは開発準備やっていきます！
