### ISSUE TITLE
曜日の繰り返し設定

### ISSUE THREAD

**Issue by susatthi** [IkemotoNanako/repeat_notification_app#10]
- 次の要件の実装を行う。
- 必要に応じてPRを分割してよい。
- デザインは仮なので作り込みすぎないこと。
- ワイヤーフレームは [Figma](https://www.figma.com/file/3iH4IrxIF7qOYFcd79J82d/%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=0-1&mode=design&t=8OyaDQOrGMmVOCfw-0) を参照すること。

## 要件

- ルーティーン登録画面／編集画面
  - 曜日の繰り返し指定ができること

**Comment by susatthi** [comment]
@IkemotoNanako 

レビューしてもらい、マージもしたのですが、、
実は、ルーティーン編集画面→曜日繰り返し設定画面が、宣言的ナビゲーションではなく統一性がないのがよくないと思っていました。
宣言的ナビゲーションを使っていない理由は、go_router と riverpod を組み合わせたときの Widget Tree の制約によるもの（Widget Tree 上ルーティーン編集画面と曜日繰り返し設定画面が兄弟関係で別々の ProviderScope になっているため）ですが、これがパッと見理解しづらいです。

go_router の ShellRoute を使って、Widget Tree 上、ルーティーン編集画面と曜日繰り返し設定画面が同じ ProviderScope の配下に出来ないか検討したのですが、良い方法が見つかりませんでした。

そこで、私にはなじみのある auto_route を使ってみたら、うまくできて、すべてが宣言的ナビゲーションで統一できました！

auto_route を使った新しい実装にしても良いでしょうか？
それとも、今までの go_router を使った実装のほうがよいでしょうか？

下記は、go_router と auto_route の Widget Tree の比較です。

（1）go_router で、一部宣言的ナビゲーションを使わない（現状の最新のコード）
（2）go_router ですべて宣言的ナビゲーション、ルーティーン編集画面と曜日繰り返し設定画面が別々の ProviderScope になってしまっている。
（3）auto_route ですべて宣言的ナビゲーション、良い感じ

（1）|（2）|（3）
--|--|--
![CleanShot 2024-02-20 at 07 19 39@2x](https://github.com/IkemotoNanako/repeat_notification_app/assets/13707135/8930fc52-0d4d-4163-bec5-244d62616f90)|![CleanShot 2024-02-20 at 07 20 33@2x](https://github.com/IkemotoNanako/repeat_notification_app/assets/13707135/7c78dced-852d-4ebd-b62b-f9b7a4c40d17)|![CleanShot 2024-02-20 at 07 17 19@2x](https://github.com/IkemotoNanako/repeat_notification_app/assets/13707135/76b81087-3fbd-47d9-b3f1-7c5ab1030717)

**Comment by IkemotoNanako** [comment]
@susatthi 
提案通り、３が良さそうです！
大変そうでなければよろしくお願いします！

**Comment by susatthi** [comment]
@IkemotoNanako 

３でやります！
