### ISSUE TITLE
ルーティーンの登録

### ISSUE THREAD

**Issue by susatthi** [IkemotoNanako/repeat_notification_app#2]
- 次の要件の実装を行う。
- 必要に応じてPRを分割してよい。
- デザインは仮なので作り込みすぎないこと。
- ワイヤーフレームは [Figma](https://www.figma.com/file/3iH4IrxIF7qOYFcd79J82d/%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=0-1&mode=design&t=8OyaDQOrGMmVOCfw-0) を参照すること。
- 繰り返しは本Issueの対象外。

## 要件

- ルーティーン一覧画面は仮で作っておく
- ルーティーン登録画面
  - 時間を指定できること
  - サウンド通知のON/OFFの切替ができること
  - プッシュ通知のON/OFFの切替ができること

**Comment by susatthi** [comment]
@IkemotoNanako 

最初のコメントに要件を記載しました。

[Figma](https://www.figma.com/file/3iH4IrxIF7qOYFcd79J82d/%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%A2%E3%83%97%E3%83%AA?type=design&node-id=0-1&mode=design&t=8OyaDQOrGMmVOCfw-0) を確認した上で要件について確認させてください。

① Figmaはイメージであり、必ずこのデザインで実装する必要はない、という認識であってますか？
② 2枚目のルーティーン登録画面で時間指定のデザインがないので追加してほしいです。
③ ルーティーン編集画面がないので追加してほしいです。
④ （本Issueと関係ないですが）3枚目の繰り返し設定画面にはどう遷移するイメージでしょうか？繰り返しでONにしたら遷移？繰り返しはボタン or ListTileにする？
⑤ ルーティーンの情報は shared_preferences を使う想定ですか？shared_preferences は key=value の簡単な構造しか登録できず、保存したデータの検索にも不向きです。FirestoreかローカルDB（isarなど）のどちらかにしたほうがよいと思います。ご意見ください！

**Comment by IkemotoNanako** [comment]
@susatthi 
ありがとうございます！！

1. あってます！色以外は自分からはこれ以上変えない気がします！メソッドだけ作っていただく感じでも大丈夫です！
2. 追加しました！黒いのは無視してください！関数だけの依頼のつもりでしたので作らなくても大丈夫です！
3. 編集も追加と同じように２画面目に飛びます
4. 繰り返し欄タップで遷移にFigmaを変更しました！
5. 教えてくださりありがとうございます！ローカルDBの方が良さそうです！もしよろしければ、コード内にたくさんコメントをつけるか、記事を書いていただけると嬉しいです！

返信遅くなってすみません💦
テキトーいじったらGitHubのメンションが会社のメールにしか来ないようになってしまったので、もしよろしければSlackでもお声がけください。。。（このプロジェクトには個人メールアドレスにも通知が来るようにさっき設定しました。。。）

**Comment by IkemotoNanako** [comment]
@susatthi 
どこまで依頼するか認識合ってなかったですね。。。
Figmaはあくまで関数を作る理由の参考で、UIまで任せるつもりはなかったです
最初は、UI作るの退屈かな〜、ローカル保存と通知機能なら記事にしやすいかな〜、と思って画面は自分で実装しようと思ってました！！
また、画面作成だけ他の傭兵さんに頼むという手も考えてました！

すささんはどうしたいですか？

**Comment by susatthi** [comment]
@IkemotoNanako 

> 1. あってます！色以外は自分からはこれ以上変えない気がします！メソッドだけ作っていただく感じでも大丈夫です！

承知しました！
デザインはマテリアルデザイン3のデフォルトに近い形で実装しておきます！

> 2. 追加しました！黒いのは無視してください！関数だけの依頼のつもりでしたので作らなくても大丈夫です！

ありがとうございます！

> 3. 編集も追加と同じように２画面目に飛びます

承知しました！

> 4. 繰り返し欄タップで遷移にFigmaを変更しました！

確認しました！

> 5. 教えてくださりありがとうございます！ローカルDBの方が良さそうです！もしよろしければ、コード内にたくさんコメントをつけるか、記事を書いていただけると嬉しいです！

ローカルDBの isar にしますね！
https://pub.dev/packages/isar

**Comment by susatthi** [comment]
@IkemotoNanako 

>どこまで依頼するか認識合ってなかったですね。。。
Figmaはあくまで関数を作る理由の参考で、UIまで任せるつもりはなかったです
最初は、UI作るの退屈かな〜、ローカル保存と通知機能なら記事にしやすいかな〜、と思って画面は自分で実装しようと思ってました！！
また、画面作成だけ他の傭兵さんに頼むという手も考えてました！
すささんはどうしたいですか？

なるほど！そういうことだったんですね！
UIなし関数だけよりも、簡単なUIも実装したほうがやりやすいのでやります！関数だけ作っても結局呼び出し元も作る必要があって簡単なUIを作るのも変わらないし、なんなら動作確認のしやすさを考えてもUIあったほうがうれしいです！

**Comment by IkemotoNanako** [comment]
承知しました！UIもよろしくお願いします！！

**Comment by susatthi** [comment]
@IkemotoNanako 

対応完了したのでクローズしました！
